### ISSUE TITLE
Driving modes!

### ISSUE THREAD

**Issue by camilo86** [FRC125/NU16#11]
Since we are using TalonSRX and its new functionalities (motion profile, distance, etc), we need to setup the driving mode before it can be used. We need to go through the code and make sure that our Drivetrain Talons are being place in the correct mode at the beginning of auto and teleop. Lets NOT get our Drivetrain talons stuck in motion profile mode while in teleop!

**Comment by lydiaxing** [comment]
Resolved due to: 8304e052b5ef129749f3342f381d984e8faee10e
