### ISSUE TITLE
Multi Target Tracking

### ISSUE THREAD

**Issue by schreiaj** [FRC125/NU16#42]
On the field we will see multiple targets, we need to identify which one we want to target and properly identify it.

**Comment by ashergottlieb** [comment]
I added about 4 lines of code so that it chooses the largest detected object, it has yet to be tested though. The largest target will be the closest and the easiest to align to.
457bf3b33543b6053f539e6caccb632b71f60bc6

**Comment by camilo86** [comment]
We tested https://github.com/FRC125/NU16/commit/457bf3b33543b6053f539e6caccb632b71f60bc6 . Works
