### ISSUE TITLE
Gun Cam when lights turn on

### ISSUE THREAD

**Issue by schreiaj** [FRC125/NU16#45]
In order to facilitate tuning of vision, have a way of snapping pictures while on field and saving them to the RoboRIO or PC.

**Comment by ashergottlieb** [comment]
Added snap.py utility to VISION16
[snap.py](https://github.com/FRC125/VISION16/blob/master/PyScripts/snap.py)

**Comment by schreiaj** [comment]
@totallyashes Are we currently using the python code for vision?

**Comment by camilo86** [comment]
@schreiaj snap.py is meant to be used before matches. Assuming we have the ip camera connected to a laptop, we can quickly go to the field with just a laptop before a match and take a bunch of pictures. We can then import them to Grip and adjust our filters.

**Comment by schreiaj** [comment]
@camilo86 Ok. I'll also probably be using them for training data too.
