### ISSUE TITLE
Camera offset

### ISSUE THREAD

**Issue by camilo86** [FRC125/NU16#50]
The camera will no longer be in the center of the arm. It will be placed somewhere in the left or right of the robot. We need to add/subtract some constant from the x-coordinate of the target in here https://github.com/FRC125/NU16/blob/master/src/com/nutrons/stronghold/Robot.java#L224

Turns out that this constant is proportional to the distance away from the target. We are going to need some magicmatics here :laughing:

**Comment by schreiaj** [comment]
So, I'm sure we could theory this out but frankly my trig is atrocious. Take a freaking webcam, a rolling chair (maybe one with a majority of it's wheels?), and, idk, a piece of tape on the wall. Record a video as you move the camera forward and backward. If you're feeling particularly lazy use dark tape on a light wall and do a HoughLines filter on it to find vertical lines, plot the difference between the centerline and that vertical line.

**Comment by ghost** [comment]
So the good thing about coordinate planes and zero lines is the fact that they are arbitrary in nature. All we need is the exact offset from the center (which I assume mechanical knows ahead of time), and from there we can modify what the robot understands as "zero." In theory, I am fairly certain that this can be accomplished by simply modifying the y-intercept in our angle function, however we would definitely need to test on the robot to confirm.

**Comment by camilo86** [comment]
There is a couple issues with that (as we saw during the first couple
matches in arizona) definitely worth a second shot.

**Comment by ghost** [comment]
Also, before we mount the camera itself, we should try to get one without the adjustable blur dial (or whatever you call that thing) on the frame as we saw some dramatic issues with that during our first couple of matches. I suspect the frantic manual tuning before every match will be costly and inefficient to say the least.

**Comment by ashergottlieb** [comment]
Added experimental functions to calculate offset for us: 0a1172dc9879722ecbc6a1f94e071106c8cc9b3f
getHorizontalAngle calculates the distance from the camera to target (using vertical position on screen), then the robot to target, and then finally using those two and the distance between the camera and the robot (its center), it can calculate the angle to the target from the robot.
All done with constants and math, no regression.
Still have yet to test, there will probably be bugs.

**Comment by camilo86** [comment]
Done due to: ad6491520c98ca5e71b22cd664e1903642b7bd66
