### ISSUE TITLE
FInd the correct encoder's distance per pulse 

### ISSUE THREAD

**Issue by camilo86** [FRC125/NU16#6]
As of right now, we are using an estimation of our encoder's distancePerPulse [here](https://github.com/FRC125/NU16/blob/paths/src/com/nutrons/stronghold/subsystems/Drivetrain.java#L50-L51). We need to find an accurate representation of our distancePerPulse so that our autonomous driving can be more accurate

**Comment by cappuccinocat** [comment]
Fixed due to: 9c4d97e73c49b72a91774dcc09bb16019bf95f9a
